# Generated by Django 5.2 on 2026-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='media/category_images/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
